# Generated by Django 3.1.7 on 2021-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=255, verbose_name='Todo Name')),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
